name: tts-metrics
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.1
  - aiosignal=1.4.0
  - aom=3.9.1
  - async-timeout=5.0.1
  - attrs=25.4.0
  - audioread=3.0.1
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - cpython=3.10.19
  - cycler=0.12.1
  - datasets=2.16.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - decorator=5.2.1
  - dill=0.3.7
  - ffmpeg=8.0.0
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - fsspec=2023.10.0
  - gdk-pixbuf=2.44.4
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - glog=0.7.1
  - glslang=16.0.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hf-xet=1.2.0
  - hpack=4.1.0
  - huggingface_hub=0.36.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - joblib=1.5.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.16.0
  - libcxx=21.1.4
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libogg=1.3.5
  - libopenblas=0.3.25
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopenvino=2025.2.0
  - libopenvino-arm-cpu-plugin=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libparquet=21.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libusb=1.0.29
  - libutf8proc=2.11.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - llvmlite=0.45.1
  - lz4-c=1.10.0
  - mpg123=1.32.9
  - msgpack-python=1.1.2
  - multidict=6.6.3
  - multiprocess=0.70.15
  - munkres=1.1.4
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - nomkl=3.0
  - numba=0.62.1
  - numpy=1.26.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.5.4
  - orc=2.2.1
  - packaging=25.0
  - pango=1.56.4
  - patsy=1.0.2
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - pooch=1.8.2
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - psutil=5.9.6
  - pthread-stubs=0.4
  - pugixml=1.15
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pyarrow-hotfix=0.7
  - pycparser=2.22
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - pysoundfile=0.13.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.19
  - python-tzdata=2025.2
  - python-xxhash=3.6.0
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - re2=2025.08.12
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.7.2
  - scipy=1.11.3
  - sdl2=2.32.56
  - sdl3=3.2.24
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - shaderc=2025.4
  - six=1.17.0
  - snappy=1.2.2
  - soxr=0.1.3
  - soxr-python=1.0.0
  - spirv-tools=2025.4
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - tbb=2022.2.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - tqdm=4.66.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyascii==0.3.3
      - babel==2.17.0
      - bangla==0.0.5
      - blinker==1.9.0
      - blis==1.2.1
      - bnnumerizer==0.0.2
      - bnunicodenormalizer==0.1.7
      - cachetools==6.2.1
      - catalogue==2.0.10
      - click==8.3.0
      - cloudpathlib==0.23.0
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contourpy==1.2.1
      - coqpit==0.0.17
      - cymem==2.0.11
      - cython==3.1.6
      - dateparser==1.1.8
      - docopt==0.6.2
      - einops==0.8.1
      - encodec==0.1.1
      - flask==3.0.0
      - flask-cors==4.0.0
      - flatbuffers==25.9.23
      - g2pkk==0.1.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.27.0
      - google-api-python-client==2.185.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.71.0
      - googlemaps==4.10.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - gruut==2.2.3
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - hangul-romanize==0.1.0
      - httplib2==0.31.0
      - humanfriendly==10.0
      - inflect==7.5.0
      - itsdangerous==2.2.0
      - jamo==0.4.1
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiwer==4.0.0
      - jsonlines==1.2.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langcodes==3.5.0
      - language-data==1.3.0
      - librosa==0.10.0
      - marisa-trie==1.3.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - murmurhash==1.0.13
      - narwhals==2.9.0
      - networkx==2.8.8
      - nltk==3.9.2
      - num2words==0.5.14
      - onnxruntime==1.23.1
      - openai-whisper==20231117
      - pandas==1.5.3
      - piper-tts==1.3.0
      - preshed==3.0.10
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydeck==0.9.1
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pypinyin==0.55.0
      - pysbd==0.3.4
      - python-crfsuite==0.9.11
      - rapidfuzz==3.14.1
      - referencing==0.37.0
      - regex==2025.10.23
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - shellingham==1.5.4
      - smart-open==7.4.1
      - smmap==5.0.2
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - streamlit==1.50.0
      - sudachidict-core==20250825
      - sudachipy==0.6.10
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - thinc==8.3.4
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.0
      - torchaudio==2.9.0
      - trainer==0.0.36
      - transformers==4.57.1
      - tts==0.22.0
      - typeguard==4.4.4
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tzlocal==5.3.1
      - umap-learn==0.5.7
      - unidecode==1.4.0
      - uritemplate==4.2.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.1.3
      - wrapt==2.0.0
prefix: /Users/prabhavsingh/miniconda3/envs/tts-metrics
